import "./globals.css";
import { Roboto_Flex } from "next/font/google";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"], // You can add more subsets if needed
  variable: true, // Enable variable font
  weights: [500, 800], // Specify weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: robotoFlex.style.fontFamily }}>
        {children}
      </body>
    </html>
  );
}
